name: sized_context_example
description: A new Flutter application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  sized_context:
    path: ../

flutter:
  uses-material-design: true
